# Generated by Django 5.1.1 on 2025-02-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
        migrations.AddField(
            model_name='internalassessmentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student'),
        ),
        migrations.AddField(
            model_name='internalassessmentmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subject'),
        ),
        migrations.AddField(
            model_name='internalassessmentmarks',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
        migrations.AddField(
            model_name='submission_assgn',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.add_assignment'),
        ),
        migrations.AddField(
            model_name='submission_assgn',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('teacher', 'student', 'subject', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='submission_assgn',
            unique_together={('student', 'assignment')},
        ),
    ]
